name: Publiser nettside

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hent kode
        uses: actions/checkout@v4

      - name: Set opp Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render nettsida
        run: quarto render

      - name: Last opp artefakt
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Publiser til GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
